server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: user-service
          uri: lb://user-service # 路由的目标地址 lb就是负载均衡 后面跟服务名
          predicates: # 路由断言 判断请求是否符合路由规则的条件
            - Path=/user/** # 按照路径匹配
          filter:
            - AddRequestHeader=Truth, Deng
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/user/**